#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ]; then
  AUTH="password"
else
  AUTH="none"
  echo "starting with no password"
fi

if [ -n "${WORKSPACE_PATH}" ]; then
	WORKSPACE="/config/workspace"
else
	WORKSPACE="${WORKSPACE_PATH}"
fi

exec \
	s6-setuidgid abc \
		/usr/bin/code-server \
			--port 8443 \
			--user-data-dir /config/data \
			--extensions-dir /config/extensions \
			--disable-telemetry \
			--disable-updates \
			--auth "${AUTH}" \
			--cert "${CERT}" \
			--cert-key "${CERT_KEY}" \
			"${WORKSPACE}"
