#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ]; then
	AUTH="password"
else
	AUTH="none"
	echo "starting with no password"
fi

exec \
	s6-setuidgid abc \
		/app/code-server/code-server \
			--host 0.0.0.0 \
			--port 8443 \
			--user-data-dir /config/data \
			--extensions-dir /config/extensions \
			--disable-telemetry \
			--disable-updates \
			--auth ${AUTH} \
			/config/workspace
