#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ] || [ -n "${HASHED_PASSWORD}" ]; then
    AUTH="password"
else
    AUTH="none"
    echo "starting with no password"
fi

if [ -z ${PROXY_DOMAIN+x} ]; then
    PROXY_DOMAIN_ARG=""
else
    PROXY_DOMAIN_ARG="--proxy-domain=${PROXY_DOMAIN}"
fi

if [ -n "${S3_ACCESS_KEY_ID}" ]; then
    printf '{"folders": [ {"path": "%s/workspace"}, {"path": "/mnt/s3"} ]}\n' "${HOME}" > "${HOME}/default.code-workspace"
    chmod 600 "${HOME}/default.code-workspace"
    DEFAULT_WORKSPACE2="${HOME}/default.code-workspace"
else
    DEFAULT_WORKSPACE2=${DEFAULT_WORKSPACE}
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 8443" \
        s6-setuidgid root \
            /app/code-server/bin/code-server \
                --bind-addr 0.0.0.0:8443 \
                --user-data-dir "${HOME}/data" \
                --extensions-dir "${HOME}/extensions" \
                --disable-telemetry \
                --auth "${AUTH}" \
                "${PROXY_DOMAIN_ARG}" \
                "${DEFAULT_WORKSPACE2:-${HOME}/workspace}"
