#!/usr/bin/with-contenv bash

mkdir -p /config/{extensions,data,workspace,.ssh}

if [ -n "${SUDO_PASSWORD}" ]; then
  echo "setting up sudo access"
  if ! grep -q 'abc' /etc/sudoers; then
    echo "adding abc to sudoers"
    echo "abc ALL=(ALL:ALL) ALL" >> /etc/sudoers
  fi
  echo "setting sudo password"
  echo -e "${SUDO_PASSWORD}\n${SUDO_PASSWORD}" | passwd abc
fi

# permissions
chown -R abc:abc \
	/config
